CFLAGS=-Wall -g

all:
	cc $(CFLAGS) ex3.c -o ex3
	cc $(CFLAGS) ex4.c -o ex4
	cc $(CFLAGS) ex5.c -o ex5
	cc $(CFLAGS) ex6.c -o ex6
	cc $(CFLAGS) ex7.c -o ex7
	cc $(CFLAGS) ex8.c -o ex8

clean:
	rm -f ex3 ex4 ex5 ex6 ex7 ex8